# Generated by Django 2.1 on 2019-08-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Models',
            new_name='Movie',
        ),
    ]
