# Generated by Django 2.1 on 2019-08-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190821_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
