# Generated by Django 2.1 on 2019-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description_test',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='metascore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
