# Generated by Django 2.1 on 2019-08-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190821_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description_test',
            new_name='description',
        ),
    ]
