# Generated by Django 2.1 on 2019-08-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190821_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(default='', max_length=2083),
            preserve_default=False,
        ),
    ]
